package com.example.autonuoma.mybatis.dao;

import com.example.autonuoma.mybatis.model.Automobilis;
import org.mybatis.cdi.Mapper;

import java.util.List;
@Mapper
public interface AutomobilisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.AUTOMOBILIS
     *
     * @mbg.generated Mon May 09 00:34:03 EEST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.AUTOMOBILIS
     *
     * @mbg.generated Mon May 09 00:34:03 EEST 2022
     */
    int insert(Automobilis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.AUTOMOBILIS
     *
     * @mbg.generated Mon May 09 00:34:03 EEST 2022
     */
    Automobilis selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.AUTOMOBILIS
     *
     * @mbg.generated Mon May 09 00:34:03 EEST 2022
     */
    List<Automobilis> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.AUTOMOBILIS
     *
     * @mbg.generated Mon May 09 00:34:03 EEST 2022
     */
    int updateByPrimaryKey(Automobilis record);
}