package com.example.autonuoma.mybatis.dao;

import com.example.autonuoma.mybatis.model.Vairuotojas;
import org.mybatis.cdi.Mapper;

import java.util.List;
@Mapper
public interface VairuotojasMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.VAIRUOTOJAS
     *
     * @mbg.generated Mon May 09 00:34:03 EEST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.VAIRUOTOJAS
     *
     * @mbg.generated Mon May 09 00:34:03 EEST 2022
     */
    int insert(Vairuotojas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.VAIRUOTOJAS
     *
     * @mbg.generated Mon May 09 00:34:03 EEST 2022
     */
    Vairuotojas selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.VAIRUOTOJAS
     *
     * @mbg.generated Mon May 09 00:34:03 EEST 2022
     */
    List<Vairuotojas> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.VAIRUOTOJAS
     *
     * @mbg.generated Mon May 09 00:34:03 EEST 2022
     */
    int updateByPrimaryKey(Vairuotojas record);
}